/*var n = 0; 
while(n != 5){ 
    n = Math.floor((Math.random() * 10)); 
    console.log(n) 
}

var n = 0; 
while(n != 5){ 
    n = Math.random(); //generate a random number between 0 and 1 exclusive of 1. 
    n = n * 10;//multiply the number generated by 10 
    n = Math.floor(n); //round down 
    console.log(n); //print the final number 
}

var x = 0; 
do{ 
 x+= 1; 
 console.log(x) 
}while(x < 10)*/

    var readlineSync = require('readline-sync'); //make the module just installed available for use in our program 
    var answer; //declare variable named answer; 
    do{ 
    //use question() function to read input and assign the value to answer 
    answer = readlineSync.question('What should I do? [Type "exit" for me to quit]: '); 
    console.log('You asked me to '+ answer) 
    }while(answer != 'exit')



        var readline = require('readline'); //load the readline module into the runtime environment 
        //Next, create the input/output interface as required by readline module. 
        var readlineAsync = readline.createInterface({ 
        input: process.stdin, 
        output: process.stdout 
        }); 
        //Next, declare and define a function named recursiveReadLineAsync 
        function recursiveReadLineAsync() { 
        readlineAsync.question('What should I do? [Type "exit" for me to quit]: ', function (answer){ 
        console.log('You asked me to ' + answer) 
        if (answer == 'exit') //Condition for terminating further self call 
         return readlineAsync.close(); //quit the function if answer == exit 
        recursiveReadLineAsync(); //No exit yet. Call self again to ask another question. 
        }); 

        }; 
        //Finally, invoke the defined function to start the recursion 
        recursiveReadLineAsync();